# Site
name: "GIS Education | PEPFAR ICPI"
title: "PEPFAR GIS"
description: "A resource for learning how to leverage geographic tools to analyze PEPFAR data."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /gis-cluster-test2
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  keif:
    name: Keifer Gonzalez
    display_name: Keifer Gonzalez
    avatar: 'assets/images/monkey.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: 
    web: /gis-cluster-test2/tags#Keifer-Gonzalez
    description: "A senior GIS analyst working within PEPFAR ICPI through the Centers for Disease Control (CDC)."

  john:
    name: John
    display_name: John Poop
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: /gis-cluster-test2/tags#John
    twitter: https://twitter.com/wowthemesnet
    description: "I hate John."
  
  nate:
    name: Nate
    display_name: Nathanael Greene
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: 
    web: /gis-cluster-test2/tags#Nathanael-Greene
    twitter: 
    description: "The other one, not Gina."

  jess:
    name: Jessica
    display_name: Jessica Day
    avatar: 'assets/images/sloth.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: 
    web: /gis-cluster-test2/tags#Jessica-Day
    twitter: 
    description: "Ask me how to make a map."

  jim:
    name: Jimmy
    display_name: Jimmy Neutron
    avatar: 'assets/images/jimmy.jpg'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: 
    web: /gis-cluster-test2/tags#Jimmy-Neutron
    twitter: 
    description: "Will it blend?"

  storm:
    name: Ororo
    display_name: Ororo Munroe
    avatar: 'assets/images/storm.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: 
    web: /gis-cluster-test2/tags#Ororo-Munroe
    twitter: 
    description: "I can make it work."
  
  kong:
    name: King
    display_name: King Kong
    avatar: 'assets/images/kingkong.jpg'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: 
    web: /gis-cluster-test2/tags#King-Kong
    twitter: 
    description: "A real friend of the people."

  retsuko:
    name: Retsuko
    display_name: Retsuko Panda
    avatar: 'assets/images/retsuko.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: 
    web: /gis-cluster-test2/tags#Retsuko-Panda
    twitter: 
    description: "As elusive as a real life red panda."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
